[package]
name = "rust_dct"
version = "0.1.0"
authors = ["Elliott Mahler <emahler@usc.edu>"]

[dependencies]
rustfft = { git = "https://github.com/awelkie/RustFFT.git" }
num = "*"

[dev-dependencies]
rand = "*"