[package]
name = "rustdct"
version = "0.1.1"
authors = ["Elliott Mahler <join.together@gmail.com>"]

description = "RustDCT is a pure-Rust signal processing library that computes the most common Discrete Cosine Transforms"

repository = "https://github.com/ejmahler/rust_dct"

keywords = ["dct", "mdct", "discrete", "cosine", "jpeg"]
categories = ["algorithms", "compression", "multimedia::encoding", "science", "visualization"]
license = "MIT OR Apache-2.0"

[dependencies]
rustfft = "^2.0"

[dev-dependencies]
rand = "~0.3"
